package org.usfirst.frc.team4910.util;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Peg.proto

public final class Peg {
  private Peg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PegLocOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PegLoc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 peg_x = 1;</code>
     */
    int getPegX();

    /**
     * <code>int32 peg_y = 2;</code>
     */
    int getPegY();
  }
  /**
   * Protobuf type {@code PegLoc}
   */
  public  static final class PegLoc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PegLoc)
      PegLocOrBuilder {
    // Use PegLoc.newBuilder() to construct.
    private PegLoc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PegLoc() {
      pegX_ = 0;
      pegY_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PegLoc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pegX_ = input.readInt32();
              break;
            }
            case 16: {

              pegY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Peg.internal_static_PegLoc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Peg.internal_static_PegLoc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Peg.PegLoc.class, Peg.PegLoc.Builder.class);
    }

    public static final int PEG_X_FIELD_NUMBER = 1;
    private int pegX_;
    /**
     * <code>int32 peg_x = 1;</code>
     */
    public int getPegX() {
      return pegX_;
    }

    public static final int PEG_Y_FIELD_NUMBER = 2;
    private int pegY_;
    /**
     * <code>int32 peg_y = 2;</code>
     */
    public int getPegY() {
      return pegY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pegX_ != 0) {
        output.writeInt32(1, pegX_);
      }
      if (pegY_ != 0) {
        output.writeInt32(2, pegY_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pegX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pegX_);
      }
      if (pegY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pegY_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Peg.PegLoc)) {
        return super.equals(obj);
      }
      Peg.PegLoc other = (Peg.PegLoc) obj;

      boolean result = true;
      result = result && (getPegX()
          == other.getPegX());
      result = result && (getPegY()
          == other.getPegY());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PEG_X_FIELD_NUMBER;
      hash = (53 * hash) + getPegX();
      hash = (37 * hash) + PEG_Y_FIELD_NUMBER;
      hash = (53 * hash) + getPegY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Peg.PegLoc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Peg.PegLoc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Peg.PegLoc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Peg.PegLoc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Peg.PegLoc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Peg.PegLoc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Peg.PegLoc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Peg.PegLoc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Peg.PegLoc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Peg.PegLoc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Peg.PegLoc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Peg.PegLoc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Peg.PegLoc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PegLoc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PegLoc)
        Peg.PegLocOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Peg.internal_static_PegLoc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Peg.internal_static_PegLoc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Peg.PegLoc.class, Peg.PegLoc.Builder.class);
      }

      // Construct using Peg.PegLoc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pegX_ = 0;

        pegY_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Peg.internal_static_PegLoc_descriptor;
      }

      public Peg.PegLoc getDefaultInstanceForType() {
        return Peg.PegLoc.getDefaultInstance();
      }

      public Peg.PegLoc build() {
        Peg.PegLoc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Peg.PegLoc buildPartial() {
        Peg.PegLoc result = new Peg.PegLoc(this);
        result.pegX_ = pegX_;
        result.pegY_ = pegY_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Peg.PegLoc) {
          return mergeFrom((Peg.PegLoc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Peg.PegLoc other) {
        if (other == Peg.PegLoc.getDefaultInstance()) return this;
        if (other.getPegX() != 0) {
          setPegX(other.getPegX());
        }
        if (other.getPegY() != 0) {
          setPegY(other.getPegY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Peg.PegLoc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Peg.PegLoc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pegX_ ;
      /**
       * <code>int32 peg_x = 1;</code>
       */
      public int getPegX() {
        return pegX_;
      }
      /**
       * <code>int32 peg_x = 1;</code>
       */
      public Builder setPegX(int value) {
        
        pegX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 peg_x = 1;</code>
       */
      public Builder clearPegX() {
        
        pegX_ = 0;
        onChanged();
        return this;
      }

      private int pegY_ ;
      /**
       * <code>int32 peg_y = 2;</code>
       */
      public int getPegY() {
        return pegY_;
      }
      /**
       * <code>int32 peg_y = 2;</code>
       */
      public Builder setPegY(int value) {
        
        pegY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 peg_y = 2;</code>
       */
      public Builder clearPegY() {
        
        pegY_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PegLoc)
    }

    // @@protoc_insertion_point(class_scope:PegLoc)
    private static final Peg.PegLoc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Peg.PegLoc();
    }

    public static Peg.PegLoc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PegLoc>
        PARSER = new com.google.protobuf.AbstractParser<PegLoc>() {
      public PegLoc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PegLoc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PegLoc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PegLoc> getParserForType() {
      return PARSER;
    }

    public Peg.PegLoc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PegLoc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PegLoc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tPeg.proto\"&\n\006PegLoc\022\r\n\005peg_x\030\001 \001(\005\022\r\n\005" +
      "peg_y\030\002 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PegLoc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PegLoc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PegLoc_descriptor,
        new java.lang.String[] { "PegX", "PegY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
